/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#404a3b',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ed',
        outline: '#707a6a',
        'outline-variant': '#bfcab7',
        primary: '#004900',
        'on-primary': '#ffffff',
        'primary-container': '#006400',
        'on-primary-container': '#86df72',
        'inverse-primary': '#82db6f',
        secondary: '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        tertiary: '#004455',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005d73',
        'on-tertiary-container': '#6cd7fc',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f5',
        'on-background': '#1b1c1a',
        'surface-variant': '#e4e2de',
      },
      fontFamily: {
        heading: ['Libre Caslon Text', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'level-1': '0 2px 8px rgba(0, 73, 0, 0.04)',
        'level-2': '0 4px 20px rgba(0, 73, 0, 0.08)',
        'tactile': '0 1px 2px rgba(0, 73, 0, 0.06)',
      },
      spacing: {
        'gutter': '24px',
        'container': '1280px',
      },
    },
  },
  plugins: [],
};
